# Generated by Django 6.0.6 on 2026-06-09 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemevaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='micro_tags',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='status',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='sub_topic',
            field=models.CharField(blank=True, help_text="e.g., 'Cardiovascular System - Ventricles'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_text', models.TextField(help_text='Extracted text context or presentation text from the teacher.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.material'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_reviewed', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=1, help_text='Aptitude indicator. Range 1 (Struggling) to 5 (Mastered)')),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='core.flashcard')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'flashcard')},
            },
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
        migrations.DeleteModel(
            name='SystemEvaluation',
        ),
        migrations.DeleteModel(
            name='TestRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
