# Generated by Django 6.0.6 on 2026-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_systemevaluation_evaluator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='choice_a',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='choice_b',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='choice_c',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='choice_d',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='correct_choice',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
