# Generated by Django 6.0.6 on 2026-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_flashcard_answer_flashcard_choice_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentperformance',
            old_name='times_correct',
            new_name='attempts_count',
        ),
        migrations.RenameField(
            model_name='studentperformance',
            old_name='times_reviewed',
            new_name='correct_attempts_count',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_text',
            field=models.TextField(help_text='Extracted text or presentation text.'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='mastery_level',
            field=models.IntegerField(default=0, help_text='Range 0 (Struggling) to 5 (Mastered)'),
        ),
    ]
