# Generated by Django 6.0.6 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_times_correct_studentperformance_attempts_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
