# Generated by Django 6.0.6 on 2026-07-30 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_material_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(blank=True, help_text='Back of the card. Only used by BASIC cards.', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='card_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('BASIC', 'Basic Front/Back')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this card is next due for review.'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='interval_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='choice_a',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='choice_b',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='choice_c',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='choice_d',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='correct_choice',
            field=models.CharField(blank=True, default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(help_text='Front of the card / MCQ question stem.'),
        ),
    ]
