# Generated by Django 6.0.6 on 2026-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_flashcard_answer_flashcard_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='generation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='DONE', max_length=12),
        ),
    ]
