# Generated by Django 6.0.6 on 2026-07-30 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_material_generation_error_material_generation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('GUESSING', 'Guessing'), ('UNSURE', 'Unsure'), ('CONFIDENT', 'Confident')], max_length=10)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_ratings', to='core.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
