# Generated by Django 6.0.6 on 2026-07-30 23:41

from django.db import migrations, models


def backfill_is_learning(apps, schema_editor):
    """Existing rows that already graduated (repetitions > 0 only ever happens via the
    'correct' SM-2 branch) must stay out of learning mode, or their next lapse would
    incorrectly restart them at a 1-minute learning step and lose their review history's
    meaning. Rows with repetitions == 0 keep the field default (True), which is correct:
    they've either never graduated or their last event was a lapse."""
    StudentPerformance = apps.get_model('core', 'StudentPerformance')
    StudentPerformance.objects.filter(repetitions__gt=0).update(is_learning=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_confidencerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='is_learning',
            field=models.BooleanField(default=True, help_text='Still in short-term learning steps, not yet graduated to day-based review.'),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='learning_step',
            field=models.IntegerField(default=0, help_text='Index into the learning-steps list while is_learning is True.'),
        ),
        migrations.RunPython(backfill_is_learning, noop_reverse),
    ]
