# Generated by Django 6.0.6 on 2026-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentperformance_is_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional illustrative image (manually attached or auto-matched from the source material).', max_length=500, null=True),
        ),
    ]
