# Generated by Django 6.0.6 on 2026-07-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_flashcard_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='card_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('BASIC', 'Basic Front/Back'), ('CLOZE', 'Cloze Deletion')], default='MCQ', max_length=10),
        ),
    ]
