# Generated by Django 6.0.6 on 2026-07-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quizsession_quizattempt_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('REMEMBERING', 'Remembering'), ('UNDERSTANDING', 'Understanding'), ('APPLYING', 'Applying'), ('ANALYZING', 'Analyzing'), ('EVALUATING', 'Evaluating'), ('CREATING', 'Creating')], help_text="Bloom's Revised Taxonomy cognitive level. Teacher-facing only, never exposed to students.", max_length=15, null=True),
        ),
    ]
